/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forme.zaposleni;

import domen.Zaposleni;
import ui.forme.mode.ModeForm;

/**
 *
 * @author urosv
 */
public class FRacun extends javax.swing.JDialog {
    ModeForm mode;
    Zaposleni ulogovaniZaposleni;
    /**
     * Creates new form FRacunPravi
     */
    public FRacun(java.awt.Frame parent, boolean modal, ModeForm mode) {
        super(parent, modal);
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        postaviModForme(mode);
        postaviUlogovanogZaposlenog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnObrisiRacun = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblStavkeRacuna = new javax.swing.JTable();
        jlblRacunID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDatumKreiranja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlblUkupanIznos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblRacunKreirao = new javax.swing.JLabel();
        jpnlProizvodi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProizvodi = new javax.swing.JTable();
        jpnlInfoOProizvodu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblProizvodID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtKolicina = new javax.swing.JTextField();
        jlblNaziv = new javax.swing.JLabel();
        jlblCena = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtareaOpis = new javax.swing.JTextArea();
        jbtnDodajProizvod = new javax.swing.JButton();
        jbtnSacuvajRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtnObrisiRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnObrisiRacun.setText("OBRISI RACUN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Racun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblStavkeRacuna);

        jlblRacunID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblRacunID.setText("ID:");

        jLabel5.setText("Datum kreiranja [dd.MM.yyyy]: ");

        jLabel7.setText("Ukupan iznos:");

        jlblUkupanIznos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblUkupanIznos.setText("[jlblUkupanIznos]");

        jLabel8.setText("Racun kreirao: ");

        jlblRacunKreirao.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblRacunKreirao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblRacunID)
                    .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlblRacunKreirao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlblUkupanIznos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlProizvodi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Pregled proizvoda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblProizvodi);

        jpnlInfoOProizvodu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacije o proizvodu"));

        jLabel1.setText("ID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Opis:");

        jlblProizvodID.setText("[jlblProizvodID]");

        jLabel6.setText("Kolicina:");

        jlblNaziv.setText("[jlblNaziv]");

        jlblCena.setText("[jlblCena]");

        jtxtareaOpis.setColumns(20);
        jtxtareaOpis.setRows(5);
        jScrollPane2.setViewportView(jtxtareaOpis);

        jbtnDodajProizvod.setText("DODAJ PROIZVOD NA RACUN");

        javax.swing.GroupLayout jpnlInfoOProizvoduLayout = new javax.swing.GroupLayout(jpnlInfoOProizvodu);
        jpnlInfoOProizvodu.setLayout(jpnlInfoOProizvoduLayout);
        jpnlInfoOProizvoduLayout.setHorizontalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblProizvodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                        .addComponent(jlblCena)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jbtnDodajProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jpnlInfoOProizvoduLayout.setVerticalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblProizvodID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblNaziv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblCena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jbtnDodajProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnlProizvodiLayout = new javax.swing.GroupLayout(jpnlProizvodi);
        jpnlProizvodi.setLayout(jpnlProizvodiLayout);
        jpnlProizvodiLayout.setHorizontalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnlProizvodiLayout.setVerticalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnSacuvajRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnSacuvajRacun.setText("SACUVAJ RACUN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlProizvodi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnObrisiRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnObrisiRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnDodajProizvod;
    private javax.swing.JButton jbtnObrisiRacun;
    private javax.swing.JButton jbtnSacuvajRacun;
    private javax.swing.JLabel jlblCena;
    private javax.swing.JLabel jlblNaziv;
    private javax.swing.JLabel jlblProizvodID;
    private javax.swing.JLabel jlblRacunID;
    private javax.swing.JLabel jlblRacunKreirao;
    private javax.swing.JLabel jlblUkupanIznos;
    private javax.swing.JPanel jpnlInfoOProizvodu;
    private javax.swing.JPanel jpnlProizvodi;
    private javax.swing.JTable jtblProizvodi;
    private javax.swing.JTable jtblStavkeRacuna;
    private javax.swing.JTextField jtxtDatumKreiranja;
    private javax.swing.JTextField jtxtKolicina;
    private javax.swing.JTextArea jtxtareaOpis;
    // End of variables declaration//GEN-END:variables

    private void postaviModForme(ModeForm mode) {
        this.mode = mode;
    }

    private void postaviUlogovanogZaposlenog() {
        ulogovaniZaposleni = kontroler.KontrolerGUI.getInstanca().getUlogovaniZaposleni();
        jlblRacunKreirao.setText(ulogovaniZaposleni.toString());
    }
}
