/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forme.zaposleni;

import domen.MernaJedinica;
import domen.Proizvod;
import domen.Racun;
import domen.StavkaRacuna;
import domen.Zaposleni;
import hint.HintTextFieldUI;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KontrolerGUI;
import ui.forme.mode.ModeForm;
import ui.modeli.ModelTabeleProizvod;
import ui.modeli.ModelTabeleRacun;

/**
 *
 * @author urosv
 */
public class FRacun extends javax.swing.JDialog {

    ModeForm mode;
    Zaposleni ulogovaniZaposleni;
    double ukupanIznos;

    /**
     * Creates new form FRacunPravi
     */
    public FRacun(java.awt.Frame parent, boolean modal, ModeForm mode) {
        super(parent, modal);
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        popuniTabeluProizvod();
        postaviModForme(mode);
        postaviTabeluStavkaRacuna();
        postaviPocetneVrednosti();
        postaviUlogovanogZaposlenog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnStornirajRacun = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblStavkeRacuna = new javax.swing.JTable();
        jlblRacunID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDatumKreiranja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlblUkupanIznos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblRacunKreirao = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpnlProizvodi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProizvodi = new javax.swing.JTable();
        jpnlInfoOProizvodu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblProizvodID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtKolicina = new javax.swing.JTextField();
        jlblNaziv = new javax.swing.JLabel();
        jlblCena = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtareaOpis = new javax.swing.JTextArea();
        jbtnDodajStavku = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jlblMernaJedinica = new javax.swing.JLabel();
        jbtnSacuvajRacun = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jbtnIzmeniRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtnStornirajRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnStornirajRacun.setText("STORNIRAJ RACUN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Racun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblStavkeRacuna);

        jlblRacunID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblRacunID.setText("ID:");

        jLabel5.setText("Datum kreiranja :");

        jLabel7.setText("Ukupan iznos:");

        jlblUkupanIznos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblUkupanIznos.setText("[jlblUkupanIznos]");

        jLabel8.setText("Racun kreirao: ");

        jLabel9.setText("RSD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblRacunID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblRacunKreirao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblRacunID)
                    .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlblRacunKreirao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlblUkupanIznos)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlProizvodi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Pregled proizvoda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblProizvodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProizvodiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProizvodi);

        jpnlInfoOProizvodu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacije o proizvodu"));

        jLabel1.setText("ID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Opis:");

        jLabel6.setText("Kolicina:");

        jtxtareaOpis.setColumns(20);
        jtxtareaOpis.setRows(5);
        jScrollPane2.setViewportView(jtxtareaOpis);

        jbtnDodajStavku.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnDodajStavku.setText("DODAJ STAVKU");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jLabel10.setText("Merna jedinica:");

        javax.swing.GroupLayout jpnlInfoOProizvoduLayout = new javax.swing.GroupLayout(jpnlInfoOProizvodu);
        jpnlInfoOProizvodu.setLayout(jpnlInfoOProizvoduLayout);
        jpnlInfoOProizvoduLayout.setHorizontalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblMernaJedinica)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblProizvodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                        .addComponent(jlblCena)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jbtnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jpnlInfoOProizvoduLayout.setVerticalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblProizvodID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblNaziv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblCena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jlblMernaJedinica))
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jbtnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnlProizvodiLayout = new javax.swing.GroupLayout(jpnlProizvodi);
        jpnlProizvodi.setLayout(jpnlProizvodiLayout);
        jpnlProizvodiLayout.setHorizontalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnlProizvodiLayout.setVerticalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnSacuvajRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnSacuvajRacun.setText("SACUVAJ RACUN");
        jbtnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajRacunActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnObrisiStavku.setText("OBRISI STAVKU");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        jbtnIzmeniRacun.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnIzmeniRacun.setText("IZMENI RACUN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlProizvodi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jbtnStornirajRacun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnObrisiStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIzmeniRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSacuvajRacun))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnStornirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzmeniRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblProizvodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProizvodiMouseClicked

        ModelTabeleProizvod mtp = (ModelTabeleProizvod) jtblProizvodi.getModel();
        int obelezenProizvod = jtblProizvodi.getSelectedRow();

        if (obelezenProizvod >= 0) {

            Proizvod p = mtp.vratiOdabraniProizvod(obelezenProizvod);

            jlblProizvodID.setText(String.valueOf(p.getProizvodID()));
            jlblCena.setText(p.getCena() + " RSD");
            jlblNaziv.setText(p.getNaziv());
            jtxtareaOpis.setEditable(false);
            jtxtareaOpis.setText(p.getOpis());
            jlblMernaJedinica.setText(p.getMernaJedinica().toString());

            jtxtKolicina.setText("1");
            jtxtKolicina.grabFocus();

        }

    }//GEN-LAST:event_jtblProizvodiMouseClicked

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed

        int red = jtblProizvodi.getSelectedRow();
        if (red >= 0) {

            ModelTabeleProizvod mtp = (ModelTabeleProizvod) jtblProizvodi.getModel();

            Proizvod proizvod = mtp.vratiOdabraniProizvod(red);
            int kolicina = Integer.valueOf(jtxtKolicina.getText());

            ModelTabeleRacun mtsr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
            mtsr.dodajStavku(proizvod, kolicina);
            ukupanIznos = getUkupanIznos();

            jlblUkupanIznos.setText(ukupanIznos + "");

        }
    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        int red = jtblStavkeRacuna.getSelectedRow();
        if (red >= 0) {
            ModelTabeleRacun modelStavka = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
            modelStavka.obrisiStavku(red);

            ukupanIznos = getUkupanIznos();
            jlblUkupanIznos.setText(ukupanIznos + "");
        }
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed

    private void jbtnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajRacunActionPerformed
        // TODO: Kada se klikne u ovo dugme, postavlja se zaposleni koji je kreirao racun kao i datum racuna u sam racun
        //pa se dalje sam racun prosledjuje do kontrolera...
        ModelTabeleRacun mtp = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        Racun racun = mtp.getRacun();

        SimpleDateFormat sdf = new SimpleDateFormat("dd.mm.yyyy.");
        if (jtxtDatumKreiranja.getText().isEmpty()) {
            jtxtDatumKreiranja.setText(sdf.format(new Date()));
        }
 
        racun.setKreiraoZaposleni(ulogovaniZaposleni);
        try {
            racun.setDatumIzrade(sdf.parse(jtxtDatumKreiranja.getText().trim()));
        } catch (ParseException ex) {
            Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
        racun.setRacunID(-1);

        racun = KontrolerGUI.getInstanca().sacuvajRacun(racun);
        
        if (racun.getRacunID() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da sacuva racun");
            omoguciBtnSacuvajRacun(false);
            omoguciBtnObrisiStavku(false);
        } else {
            jlblRacunID.setText(jlblRacunID.getText() + " " + racun.getRacunID());
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da kreira racun !");
        }
    }//GEN-LAST:event_jbtnSacuvajRacunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnIzmeniRacun;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnSacuvajRacun;
    private javax.swing.JButton jbtnStornirajRacun;
    private javax.swing.JLabel jlblCena;
    private javax.swing.JLabel jlblMernaJedinica;
    private javax.swing.JLabel jlblNaziv;
    private javax.swing.JLabel jlblProizvodID;
    private javax.swing.JLabel jlblRacunID;
    private javax.swing.JLabel jlblRacunKreirao;
    private javax.swing.JLabel jlblUkupanIznos;
    private javax.swing.JPanel jpnlInfoOProizvodu;
    private javax.swing.JPanel jpnlProizvodi;
    private javax.swing.JTable jtblProizvodi;
    private javax.swing.JTable jtblStavkeRacuna;
    private javax.swing.JTextField jtxtDatumKreiranja;
    private javax.swing.JTextField jtxtKolicina;
    private javax.swing.JTextArea jtxtareaOpis;
    // End of variables declaration//GEN-END:variables

    private void postaviModForme(ModeForm mode) {
        this.mode = mode;

        switch (mode) {
            case FORM_KREIRAJ:
                postaviZaKreiranje();
                break;
            case FORM_STORNIRAJ:
                postaviZaStorniranje();
                break;
            case FORM_IZMENI:
                postaviZaIzmenu();
                break;
            case FORM_PRETRAZI:
                postaviZaPregled();
                break;
            default:
                break;
        }
    }

    private void postaviUlogovanogZaposlenog() {
        ulogovaniZaposleni = kontroler.KontrolerGUI.getInstanca().getUlogovaniZaposleni();
        jlblRacunKreirao.setText(ulogovaniZaposleni.toString());
    }

    private void popuniTabeluProizvod() {
        ModelTabeleProizvod mtp = new ModelTabeleProizvod();
        jtblProizvodi.setModel(mtp);

        //TODO: Implementirati metodu vratiSveProizvode() u kontroleru
        ArrayList<Proizvod> listaProizvoda = KontrolerGUI.getInstanca().vratiSveProizvode();

        mtp.postaviProizvode(listaProizvoda);

    }

    private void postaviTabeluStavkaRacuna() {
        ModelTabeleRacun mt = new ModelTabeleRacun(new Racun());
        jtblStavkeRacuna.setModel(mt);
    }

    private void postaviPocetneVrednosti() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        jtxtDatumKreiranja.setUI(new HintTextFieldUI("Datum u formatu dd.MM.yyyy."));
        ukupanIznos = 0;

        jlblUkupanIznos.setText(String.valueOf(ukupanIznos));
    }

    private double getUkupanIznos() {
        ModelTabeleRacun mtsr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        Racun racun = mtsr.getRacun();
        return racun.getUkupanIznos();
    }

    private void postaviZaKreiranje() {
        omoguciBtnStornirajRacun(false);
        omoguciBtnIzmeni(false);
    }

    private void omoguciBtnStornirajRacun(boolean option) {
        jbtnStornirajRacun.setVisible(option);
    }

    private void omoguciBtnSacuvajRacun(boolean option) {
        jbtnSacuvajRacun.setVisible(option);
    }

    private void omoguciBtnDodajStavku(boolean option) {
        jbtnDodajStavku.setVisible(option);
    }

    private void omoguciBtnObrisiStavku(boolean option) {
        jbtnObrisiStavku.setVisible(option);
    }

    private void postaviZaStorniranje() {
        omoguciPanelProizvodi(false);
        omoguciBtnStornirajRacun(true);
        omoguciBtnSacuvajRacun(false);
        omoguciBtnObrisiStavku(false);
    }

    private void omoguciPanelProizvodi(boolean option) {
        jpnlProizvodi.setVisible(option);
    }

    private void postaviZaIzmenu() {
        omoguciBtnSacuvajRacun(false);
        omoguciBtnStornirajRacun(false);
    }

    private void omoguciBtnIzmeni(boolean b) {
        jbtnIzmeniRacun.setVisible(false);
    }

    private void postaviZaPregled() {
        omoguciPanelProizvodi(false);

        omoguciBtnIzmeni(false);
        omoguciBtnSacuvajRacun(false);
        omoguciBtnStornirajRacun(false);
        omoguciBtnObrisiStavku(false);

    }

}
