/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forme.zaposleni;

import domen.MernaJedinica;
import domen.Proizvod;
import domen.Racun;
import domen.StavkaRacuna;
import domen.Zaposleni;
import ui.hint.HintTextFieldUI;
import java.awt.GraphicsEnvironment;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import kontroler.KontrolerGUI;
import ui.forme.mode.ModeForm;
import ui.modeli.ModelTabeleProizvod;
import ui.modeli.ModelTabeleRacun;

/**
 *
 * @author urosv
 */
public class FRacun extends javax.swing.JDialog {

    ModeForm mode;
    Zaposleni ulogovaniZaposleni;
    double ukupanIznos;

    /**
     * Creates new form FRacunPravi
     */
    public FRacun(java.awt.Frame parent, boolean modal, ModeForm mode) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        popuniTabeluProizvod();
        postaviModForme(mode);
        postaviTabeluStavkaRacuna();
        postaviPocetneVrednosti();
        postaviUlogovanogZaposlenog();
        this.pack();
        ispisiStavkeRacuna(); //TODO: obrisati

    }

    public FRacun(java.awt.Frame parent, boolean modal, ModeForm mode, Racun racunZaPrikaz) {
        super(parent, modal);
        initComponents();
        popuniTabeluProizvod();
        postaviModForme(mode);
        postaviTabeluStavkaRacuna();
        postaviPocetneVrednosti();
        postaviUlogovanogZaposlenog();
        popuniPodatkeORacunu(racunZaPrikaz);
        this.pack();
        this.setLocationRelativeTo(null);
        ispisiStavkeRacuna(); //TODO: obrisati
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnStornirajRacun = new javax.swing.JButton();
        jpnlRacun = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblStavkeRacuna = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDatumKreiranja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlblUkupanIznos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblRacunKreirao = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblRacunID = new javax.swing.JLabel();
        jpnlProizvodi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProizvodi = new javax.swing.JTable();
        jpnlInfoOProizvodu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblProizvodID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtKolicina = new javax.swing.JTextField();
        jlblNaziv = new javax.swing.JLabel();
        jlblCena = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtareaOpis = new javax.swing.JTextArea();
        jbtnDodajStavku = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jlblMernaJedinica = new javax.swing.JLabel();
        jbtnSacuvajRacun = new javax.swing.JButton();
        jbtnObrisiStavku = new javax.swing.JButton();
        jbtnOmoguciIzmenu = new javax.swing.JButton();
        jbtnIzmeniRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbtnStornirajRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnStornirajRacun.setText("STORNIRAJ RACUN");
        jbtnStornirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStornirajRacunActionPerformed(evt);
            }
        });

        jpnlRacun.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Racun", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblStavkeRacuna);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("ID:");

        jLabel5.setText("Datum kreiranja :");

        jLabel7.setText("Ukupan iznos:");

        jlblUkupanIznos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblUkupanIznos.setText("[jlblUkupanIznos]");

        jLabel8.setText("Racun kreirao: ");

        jlblRacunKreirao.setText("[jlblRacunKreirao]");

        jLabel9.setText("RSD");

        jlblRacunID.setText("[jlblRacunID]");

        javax.swing.GroupLayout jpnlRacunLayout = new javax.swing.GroupLayout(jpnlRacun);
        jpnlRacun.setLayout(jpnlRacunLayout);
        jpnlRacunLayout.setHorizontalGroup(
            jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlRacunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlRacunLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32))
                    .addGroup(jpnlRacunLayout.createSequentialGroup()
                        .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlRacunLayout.createSequentialGroup()
                                .addComponent(jlblRacunID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblRacunKreirao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpnlRacunLayout.setVerticalGroup(
            jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlRacunLayout.createSequentialGroup()
                .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jtxtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblRacunID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblRacunKreirao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jpnlRacunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlblUkupanIznos)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlProizvodi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Pregled proizvoda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jtblProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblProizvodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProizvodiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProizvodi);

        jpnlInfoOProizvodu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacije o proizvodu"));

        jLabel1.setText("ID:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        jLabel4.setText("Opis:");

        jLabel6.setText("Kolicina:");

        jtxtareaOpis.setColumns(20);
        jtxtareaOpis.setRows(5);
        jScrollPane2.setViewportView(jtxtareaOpis);

        jbtnDodajStavku.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnDodajStavku.setText("DODAJ STAVKU");
        jbtnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajStavkuActionPerformed(evt);
            }
        });

        jLabel10.setText("Merna jedinica:");

        javax.swing.GroupLayout jpnlInfoOProizvoduLayout = new javax.swing.GroupLayout(jpnlInfoOProizvodu);
        jpnlInfoOProizvodu.setLayout(jpnlInfoOProizvoduLayout);
        jpnlInfoOProizvoduLayout.setHorizontalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblMernaJedinica)
                        .addGap(0, 468, Short.MAX_VALUE))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblProizvodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                        .addComponent(jlblCena)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jbtnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlInfoOProizvoduLayout.setVerticalGroup(
            jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblProizvodID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblNaziv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlblCena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jlblMernaJedinica))
                .addGroup(jpnlInfoOProizvoduLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(jpnlInfoOProizvoduLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbtnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnlProizvodiLayout = new javax.swing.GroupLayout(jpnlProizvodi);
        jpnlProizvodi.setLayout(jpnlProizvodiLayout);
        jpnlProizvodiLayout.setHorizontalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnlProizvodiLayout.setVerticalGroup(
            jpnlProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlProizvodiLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnlInfoOProizvodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jbtnSacuvajRacun.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jbtnSacuvajRacun.setText("SACUVAJ RACUN");
        jbtnSacuvajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajRacunActionPerformed(evt);
            }
        });

        jbtnObrisiStavku.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnObrisiStavku.setText("OBRISI STAVKU");
        jbtnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiStavkuActionPerformed(evt);
            }
        });

        jbtnOmoguciIzmenu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnOmoguciIzmenu.setText("OMOGUCI IZMENU");
        jbtnOmoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOmoguciIzmenuActionPerformed(evt);
            }
        });

        jbtnIzmeniRacun.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jbtnIzmeniRacun.setText("IZMENI RACUN");
        jbtnIzmeniRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlProizvodi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnOmoguciIzmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnStornirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnObrisiStavku)
                                .addGap(68, 68, 68)
                                .addComponent(jbtnIzmeniRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSacuvajRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jbtnOmoguciIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnStornirajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvajRacun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzmeniRacun, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblProizvodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProizvodiMouseClicked

        ModelTabeleProizvod mtp = (ModelTabeleProizvod) jtblProizvodi.getModel();
        int obelezenProizvod = jtblProizvodi.getSelectedRow();

        if (obelezenProizvod >= 0) {

            Proizvod p = mtp.vratiOdabraniProizvod(obelezenProizvod);

            jlblProizvodID.setText(String.valueOf(p.getProizvodID()));
            jlblCena.setText(p.getCena() + " RSD");
            jlblNaziv.setText(p.getNaziv());
            jtxtareaOpis.setEditable(false);
            jtxtareaOpis.setText(p.getOpis());
            jlblMernaJedinica.setText(p.getMernaJedinica().toString());

            jtxtKolicina.setText("1");
            jtxtKolicina.grabFocus();

        }

    }//GEN-LAST:event_jtblProizvodiMouseClicked

    private void jbtnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajStavkuActionPerformed

        int red = jtblProizvodi.getSelectedRow();
        if (red >= 0) {

            ModelTabeleProizvod mtp = (ModelTabeleProizvod) jtblProizvodi.getModel();
            Proizvod proizvod = mtp.vratiOdabraniProizvod(red);
            int kolicina = Integer.valueOf(jtxtKolicina.getText());
            if(kolicina <= 0){
                JOptionPane.showMessageDialog(this, "Unesite kolicinu vecu od 0 !", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ModelTabeleRacun mtsr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
            mtsr.dodajStavku(proizvod, kolicina);
            ukupanIznos = getUkupanIznos();

            jlblUkupanIznos.setText(ukupanIznos + "");

        }
        ispisiStavkeRacuna();
    }//GEN-LAST:event_jbtnDodajStavkuActionPerformed

    private void jbtnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiStavkuActionPerformed
        int red = jtblStavkeRacuna.getSelectedRow();

        if (red >= 0) {
            ModelTabeleRacun mtr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
            mtr.obrisiStavku(red);
            jlblUkupanIznos.setText(mtr.getRacun().getUkupanIznos() + "");
        }

        ispisiStavkeRacuna(); //TODO: obrisati
    }//GEN-LAST:event_jbtnObrisiStavkuActionPerformed

    private void jbtnSacuvajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajRacunActionPerformed
        Racun racun = postaviVrednostiRacunaIzTabele();

        racun.postaviStavkeNaNovo();
        racun.setKreiraoZaposleni(ulogovaniZaposleni);
        try {
            postaviDatumIzrade(racun);
            racun = KontrolerGUI.getInstanca().kreirajRacun(racun);

            if (racun.getRacunID() == -1) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira racun");
                omoguciBtnSacuvajRacun(false);
                omoguciBtnObrisiStavku(false);
            } else {
                jlblRacunID.setText(racun.getRacunID() + "");
                JOptionPane.showMessageDialog(this, "Sistem je kreirao racun");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira racun");
        }
    }//GEN-LAST:event_jbtnSacuvajRacunActionPerformed

    public Racun postaviVrednostiRacunaIzTabele() {
        // TODO: Kada se klikne u ovo dugme, postavlja se zaposleni koji je kreirao racun kao i datum racuna u sam racun
        //pa se dalje sam racun prosledjuje do kontrolera...
        ModelTabeleRacun mtp = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        Racun racun = mtp.getRacun();
        return racun;
    }

    public void postaviDatumIzrade(Racun racun) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.mm.yyyy.");
        if (jtxtDatumKreiranja.getText().isEmpty()) {
            jtxtDatumKreiranja.setText(sdf.format(new Date()));
        }
        try {
            racun.setDatumIzrade(sdf.parse(jtxtDatumKreiranja.getText().trim()));
        } catch (ParseException ex) {
            throw ex;
        }
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose(); //TODO: Implementirati da se nakon zatvaranja prozra vratimo na pretrazivanje racuna
    }//GEN-LAST:event_formWindowClosing

    private void jbtnOmoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOmoguciIzmenuActionPerformed
        omoguciBtnOmoguciIzmenu(false);

        omoguciBtnIzmeni(true);
        omoguciBtnStornirajRacun(true);
        omoguciBtnSacuvajRacun(false);
        omoguciBtnObrisiStavku(true);
        omoguciPanelProizvodi(true);
        omoguciIzmenuDatuma(true);
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtnOmoguciIzmenuActionPerformed

    private void jbtnStornirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStornirajRacunActionPerformed
        int racunID = Integer.parseInt(jlblRacunID.getText().trim());
        Racun racun = new Racun(racunID, null, null, 0, false, true, null);

        boolean uspesno = KontrolerGUI.getInstanca().stornirajRacun(racun);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da stornira racun.");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da stornira racun.");
        }

        omoguciPanelProizvodi(false);
        omoguciPanelRacun(false);
        omoguciIzmenuDatuma(false);
        omoguciBtnIzmeni(false);
        omoguciBtnObrisiStavku(false);
        omoguciBtnStornirajRacun(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtnStornirajRacunActionPerformed

    private void jbtnIzmeniRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniRacunActionPerformed
        Racun racun = null;
        try {
            racun = dajRacunIzTabele();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni racun.");
            Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
            return;
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni racun.");
            Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        racun.postaviIDSvimStavkama(racun.getRacunID());

        boolean uspesno = KontrolerGUI.getInstanca().izmeniRacun(racun);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Sistem je izmenio racun.");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni racun.");
        }
    }//GEN-LAST:event_jbtnIzmeniRacunActionPerformed

    private Racun dajRacunIzTabele() throws NumberFormatException, ParseException {

        Racun racun = null;
        int racunID = Integer.parseInt(jlblRacunID.getText());
        int racunKreirao = Integer.parseInt(jlblRacunKreirao.getText());
        Zaposleni zaposleni = new Zaposleni(racunKreirao, "", "", "", false, null);
        double ukupanIznos = Double.parseDouble(jlblUkupanIznos.getText());
        Date datumIzrade = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            datumIzrade = sdf.parse(jtxtDatumKreiranja.getText());
        } catch (ParseException ex) {
            throw ex;
        }

        ModelTabeleRacun mtp = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        ArrayList<StavkaRacuna> stavke = mtp.getStavkeRacuna();

        racun = new Racun(racunID, zaposleni, datumIzrade, ukupanIznos, true, false, stavke);
        return racun;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnDodajStavku;
    private javax.swing.JButton jbtnIzmeniRacun;
    private javax.swing.JButton jbtnObrisiStavku;
    private javax.swing.JButton jbtnOmoguciIzmenu;
    private javax.swing.JButton jbtnSacuvajRacun;
    private javax.swing.JButton jbtnStornirajRacun;
    private javax.swing.JLabel jlblCena;
    private javax.swing.JLabel jlblMernaJedinica;
    private javax.swing.JLabel jlblNaziv;
    private javax.swing.JLabel jlblProizvodID;
    private javax.swing.JLabel jlblRacunID;
    private javax.swing.JLabel jlblRacunKreirao;
    private javax.swing.JLabel jlblUkupanIznos;
    private javax.swing.JPanel jpnlInfoOProizvodu;
    private javax.swing.JPanel jpnlProizvodi;
    private javax.swing.JPanel jpnlRacun;
    private javax.swing.JTable jtblProizvodi;
    private javax.swing.JTable jtblStavkeRacuna;
    private javax.swing.JTextField jtxtDatumKreiranja;
    private javax.swing.JTextField jtxtKolicina;
    private javax.swing.JTextArea jtxtareaOpis;
    // End of variables declaration//GEN-END:variables

    private void postaviModForme(ModeForm mode) {
        this.mode = mode;

        switch (mode) {
            case FORM_KREIRAJ:
                postaviZaKreiranje();
                break;
            case FORM_STORNIRAJ:
                postaviZaStorniranje();
                break;
            case FORM_IZMENI:
                postaviZaIzmenu();
                break;
            case FORM_PRETRAZI:
                postaviZaPregled();
                break;
            default:
                break;
        }
    }

    private void postaviUlogovanogZaposlenog() {
        ulogovaniZaposleni = kontroler.KontrolerGUI.getInstanca().getUlogovaniZaposleni();
        jlblRacunKreirao.setText(ulogovaniZaposleni.toString());
    }

    private void popuniTabeluProizvod() {
        ModelTabeleProizvod mtp = new ModelTabeleProizvod();
        jtblProizvodi.setModel(mtp);

        ArrayList<Proizvod> listaProizvoda;
        try {
            listaProizvoda = KontrolerGUI.getInstanca().vratiSveProizvode();
            mtp.postaviProizvode(listaProizvoda);
        } catch (Exception ex) {
            Logger.getLogger(FRacun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void postaviTabeluStavkaRacuna() {
        ModelTabeleRacun mt = new ModelTabeleRacun(new Racun());
        jtblStavkeRacuna.setModel(mt);
    }

    private void postaviPocetneVrednosti() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        jtxtDatumKreiranja.setUI(new HintTextFieldUI("Datum u formatu dd.MM.yyyy."));
        ukupanIznos = 0;

        jlblUkupanIznos.setText(String.valueOf(ukupanIznos));
    }

    private double getUkupanIznos() {
        ModelTabeleRacun mtsr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        Racun racun = mtsr.getRacun();
        return racun.getUkupanIznos();
    }

    private void postaviZaKreiranje() {
        omoguciBtnDodajStavku(true);
        omoguciBtnSacuvajRacun(true);
        omoguciBtnStornirajRacun(false);
        omoguciBtnIzmeni(false);
        omoguciBtnOmoguciIzmenu(false);
    }

    private void omoguciBtnStornirajRacun(boolean option) {
        jbtnStornirajRacun.setVisible(option);
    }

    private void omoguciBtnSacuvajRacun(boolean option) {
        jbtnSacuvajRacun.setVisible(option);
    }

    private void omoguciBtnDodajStavku(boolean option) {
        jbtnDodajStavku.setVisible(option);
    }

    private void omoguciBtnObrisiStavku(boolean option) {
        jbtnObrisiStavku.setVisible(option);
    }

    private void postaviZaStorniranje() {
        omoguciPanelProizvodi(false);
        omoguciBtnStornirajRacun(true);
        omoguciBtnSacuvajRacun(false);
        omoguciBtnObrisiStavku(false);
        omoguciBtnIzmeni(false);
        omoguciBtnOmoguciIzmenu(false);
    }

    private void omoguciPanelProizvodi(boolean option) {
        jpnlProizvodi.setVisible(option);
    }

    private void postaviZaIzmenu() {
        omoguciBtnSacuvajRacun(false);
        omoguciBtnStornirajRacun(false);
    }

    private void omoguciBtnIzmeni(boolean opcija) {
        jbtnIzmeniRacun.setVisible(opcija);
    }

    private void postaviZaPregled() {
        omoguciPanelProizvodi(false);

        omoguciBtnOmoguciIzmenu(true);
        omoguciBtnIzmeni(false);
        omoguciBtnSacuvajRacun(false);
        omoguciBtnStornirajRacun(false);
        omoguciBtnObrisiStavku(false);

    }

    private void popuniPodatkeORacunu(Racun racunZaPrikaz) {
        jlblRacunID.setText(String.valueOf(String.valueOf(racunZaPrikaz.getRacunID())));
        jlblRacunKreirao.setText("" + racunZaPrikaz.getKreiraoZaposleni().getZaposleniID());

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        jtxtDatumKreiranja.setText(sdf.format(racunZaPrikaz.getDatumIzrade()));

        ModelTabeleRacun mtr = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        mtr.setRacun(racunZaPrikaz);
        mtr.fireTableDataChanged();

        jlblUkupanIznos.setText(String.valueOf(racunZaPrikaz.getUkupanIznos()));

        omoguciIzmenuDatuma(false);

    }

    private void omoguciIzmenuDatuma(boolean b) {
        jtxtDatumKreiranja.setEnabled(b);
    }

    private void omoguciBtnOmoguciIzmenu(boolean b) {
        jbtnOmoguciIzmenu.setVisible(b);
    }

    private void omoguciPanelRacun(boolean b) {
        jpnlRacun.setEnabled(false);
    }

    private void ispisiStavkeRacuna() {
        ModelTabeleRacun mtp = (ModelTabeleRacun) jtblStavkeRacuna.getModel();
        Racun racun = mtp.getRacun();

        System.out.println("");
        for (StavkaRacuna s : racun.getStavke()) {
            System.out.println(s.getProizvod().getNaziv() + " " + s.getStatus());
        }
    }

}
