/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forme.glavna;

import kontroler.KontrolerLogike;
import ui.forme.zaposleni.FRacun;
import ui.forme.menadzer.FZaposleni;
import ui.forme.mode.FormMode;
import ui.forme.zaposleni.FRacunPretraga;

/**
 *
 * @author urosv
 */
public class FGlavnaForma extends javax.swing.JFrame {
    
    /**
     * Creates new form FGlavnaForma
     */
    public FGlavnaForma(java.awt.Frame parent) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        postaviUlogovanogZaposlenog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUlogovaniZaposleni = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuZaposleni = new javax.swing.JMenu();
        jmiKreirajZaposlenog = new javax.swing.JMenuItem();
        jmiObrisiZaposlenog = new javax.swing.JMenuItem();
        jmenuRacun = new javax.swing.JMenu();
        jmiKreirajRacun = new javax.swing.JMenuItem();
        jmiPretraziRacun = new javax.swing.JMenuItem();
        jmiIzmeniRacun = new javax.swing.JMenuItem();
        jmiStoranirajRacun = new javax.swing.JMenuItem();
        jmenuProizvod = new javax.swing.JMenu();
        jmiKreirajProizvod = new javax.swing.JMenuItem();
        jmiPretraziProizvod = new javax.swing.JMenuItem();
        jmiIzmeniProizvod = new javax.swing.JMenuItem();
        jmiObrisiProizvod = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblUlogovaniZaposleni.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblUlogovaniZaposleni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblUlogovaniZaposleni.setText("[ulogovaniZaposleni]");

        jmenuZaposleni.setText("Zaposleni");

        jmiKreirajZaposlenog.setText("Kreiraj");
        jmiKreirajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajZaposlenogActionPerformed(evt);
            }
        });
        jmenuZaposleni.add(jmiKreirajZaposlenog);

        jmiObrisiZaposlenog.setText("Obrisi");
        jmiObrisiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiZaposlenogActionPerformed(evt);
            }
        });
        jmenuZaposleni.add(jmiObrisiZaposlenog);

        jMenuBar1.add(jmenuZaposleni);

        jmenuRacun.setText("Racun");

        jmiKreirajRacun.setText("Kreiraj");
        jmiKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKreirajRacunActionPerformed(evt);
            }
        });
        jmenuRacun.add(jmiKreirajRacun);

        jmiPretraziRacun.setText("Pretrazi");
        jmiPretraziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretraziRacunActionPerformed(evt);
            }
        });
        jmenuRacun.add(jmiPretraziRacun);

        jmiIzmeniRacun.setText("Izmeni");
        jmenuRacun.add(jmiIzmeniRacun);

        jmiStoranirajRacun.setText("Storniraj");
        jmenuRacun.add(jmiStoranirajRacun);

        jMenuBar1.add(jmenuRacun);

        jmenuProizvod.setText("Proizvod");

        jmiKreirajProizvod.setText("Kreiraj");
        jmenuProizvod.add(jmiKreirajProizvod);

        jmiPretraziProizvod.setText("Pretrazi");
        jmenuProizvod.add(jmiPretraziProizvod);

        jmiIzmeniProizvod.setText("Izmeni");
        jmenuProizvod.add(jmiIzmeniProizvod);

        jmiObrisiProizvod.setText("Obrisi");
        jmiObrisiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiProizvodActionPerformed(evt);
            }
        });
        jmenuProizvod.add(jmiObrisiProizvod);

        jMenuBar1.add(jmenuProizvod);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblUlogovaniZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblUlogovaniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPretraziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretraziRacunActionPerformed
        FRacunPretraga formPretragaRacuna = new FRacunPretraga(this, false);
        formPretragaRacuna.setVisible(true);
    }//GEN-LAST:event_jmiPretraziRacunActionPerformed

    private void jmiObrisiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiProizvodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiObrisiProizvodActionPerformed

    private void jmiKreirajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajZaposlenogActionPerformed
        //TODO: Implementirati mogucnost da se salje enumeracija koja odredjuje sta ce na novoj formi biti omoguceno a sta ne
        FZaposleni zaposleniForma = new FZaposleni(this, false);
        zaposleniForma.setVisible(true);
    }//GEN-LAST:event_jmiKreirajZaposlenogActionPerformed

    private void jmiObrisiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiZaposlenogActionPerformed
        //TODO: Implementirati mogucnost da se salje enumeracija koja odredjuje sta ce na novoj formi biti omoguceno a sta ne
        FZaposleni zaposleniForma = new FZaposleni(this, false);
        zaposleniForma.setVisible(true);
    }//GEN-LAST:event_jmiObrisiZaposlenogActionPerformed

    private void jmiKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKreirajRacunActionPerformed
        FRacun formaRacun = new FRacun(this, false, FormMode.FORM_KREIRAJ);
        formaRacun.setVisible(true);
    }//GEN-LAST:event_jmiKreirajRacunActionPerformed

    private void pokreniFormuZaposleni() {
        FZaposleni zaposleniForma = new FZaposleni(this, false);
        zaposleniForma.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FGlavnaForma form = new FGlavnaForma(new javax.swing.JFrame());
                form.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlblUlogovaniZaposleni;
    private javax.swing.JMenu jmenuProizvod;
    private javax.swing.JMenu jmenuRacun;
    private javax.swing.JMenu jmenuZaposleni;
    private javax.swing.JMenuItem jmiIzmeniProizvod;
    private javax.swing.JMenuItem jmiIzmeniRacun;
    private javax.swing.JMenuItem jmiKreirajProizvod;
    private javax.swing.JMenuItem jmiKreirajRacun;
    private javax.swing.JMenuItem jmiKreirajZaposlenog;
    private javax.swing.JMenuItem jmiObrisiProizvod;
    private javax.swing.JMenuItem jmiObrisiZaposlenog;
    private javax.swing.JMenuItem jmiPretraziProizvod;
    private javax.swing.JMenuItem jmiPretraziRacun;
    private javax.swing.JMenuItem jmiStoranirajRacun;
    // End of variables declaration//GEN-END:variables

    private void postaviUlogovanogZaposlenog() {
        jlblUlogovaniZaposleni.setText("Trenutno ulogovan: " + KontrolerLogike.getInstanca().getZaposleni());
    }
}
